# Generated by Django 4.2.6 on 2025-12-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='scenario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
