# Generated by Django 5.2.9 on 2025-12-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_userprofile_scenario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresponse',
            old_name='emotion_score',
            new_name='emotion_intensity',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='sentiment',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='sentiment_label',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
