# Generated by Django 5.2.9 on 2025-12-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_rename_emotion_score_userresponse_emotion_intensity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='dominant_emotion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
