# Generated by Django 5.2.9 on 2025-12-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_userresponse_dominant_emotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='dominant_emotion',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='emotion_intensity',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='sentiment_label',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='sentiment_score',
        ),
    ]
